workflows:
  version: 2
  build_and_test:
    jobs:
      - build-test
jobs:
  build-test:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run build
          command: npm build    
      - run:
          name: Run Tests
          command: npm test