workflows:
  version: 2
  
  build-test-deploy:
    jobs:
      - build-test
      - hold-build-test:
          type: approval
          requires:
            - build-test
      - deploys:           
          requires:
            - hold-build-test 

jobs:
  build-test:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run build
          command: npm build    
      - run:
          name: Run Tests
          command: npm test
  deploys:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
    - checkout
    - run:
      name: App Deployment
      command: echo "SUCCESS - Deployment to Azure"      